apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: modresort-ingress
  labels:
    app: modresort-app
spec:
  rules: 
  - http:
      paths:
        - path: /
        backend:
          serviceName: modresort-service
          servicePort: 9080
