apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: modresort-ingress
  namespace: ingress-basic
  labels:
    app: modresort-app
spec:
  rules: 
  - http:
      paths:
      - path: /modresort
        backend:
          serviceName: modresort-service
          servicePort: 9080
